export default {
	extends: ['stylelint-config-standard-scss', 'stylelint-config-recess-order'],
	plugins: ['stylelint-scss'],
	rules: {
		indentation: 'tab',
		'string-quotes': 'double',
		'no-duplicate-selectors': true,
		'color-hex-case': 'lower',
		'color-hex-length': 'short',
		'color-named': 'never',
		'selector-combinator-space-after': 'always',
		'selector-attribute-quotes': 'always',
		'selector-attribute-operator-space-before': 'never',
		'selector-attribute-operator-space-after': 'never',
		'selector-attribute-brackets-space-inside': 'never',
		'declaration-block-trailing-semicolon': 'always',
		'declaration-no-important': true,
		'declaration-colon-space-before': 'never',
		'declaration-colon-space-after': 'always',
		'number-leading-zero': 'always',
		'function-url-quotes': 'always',
		'font-weight-notation': 'numeric',
		'comment-whitespace-inside': 'always',
		'rule-empty-line-before': [
			'always',
			{
				except: ['first-nested'],
				ignore: ['after-comment'],
			},
		],
		'selector-pseudo-element-colon-notation': 'double',
		'selector-pseudo-class-parentheses-space-inside': 'never',
		'media-feature-range-operator-space-before': 'always',
		'media-feature-range-operator-space-after': 'always',
		'media-feature-parentheses-space-inside': 'never',
		'media-feature-colon-space-before': 'never',
		'media-feature-colon-space-after': 'always',
		'scss/at-rule-no-unknown': true,
		'scss/dollar-variable-colon-space-after': 'always',
		'scss/dollar-variable-colon-space-before': 'never',
		'scss/dollar-variable-no-missing-interpolation': true,
		'scss/double-slash-comment-whitespace-inside': 'always',
		'scss/operator-no-newline-before': true,
		'scss/operator-no-unspaced': true,
		'scss/selector-no-redundant-nesting-selector': true,
		'at-rule-empty-line-before': [
			'always',
			{
				except: ['blockless-after-same-name-blockless', 'first-nested'],
				ignore: ['after-comment'],
			},
		],
		'max-nesting-depth': 3,
		'selector-max-compound-selectors': 4,
		'selector-max-id': 0,
		'shorthand-property-no-redundant-values': true,
		'value-no-vendor-prefix': true,
		'property-no-vendor-prefix': true,
		'declaration-block-no-redundant-longhand-properties': true,
		'declaration-block-single-line-max-declarations': 1,
		'block-closing-brace-newline-after': [
			'always',
			{
				ignoreAtRules: ['if', 'else'],
			},
		],
		'order/properties-alphabetical-order': null,
	},
	ignoreFiles: ['dist/**/*', 'build/**/*', 'node_modules/**/*'],
};
