export const selectFeedPosts = (state) => state.posts.feedPosts;
export const selectMyFeedPosts = (state) => state.posts.myFeedPosts;
export const selectCurrentPost = (state) => state.posts.currentPost;
export const selectComments = (state) => state.posts.comments;
export const savedPosts = (state) => state.posts.savedPosts;
export const selectLoading = (state) => state.posts.loading;
export const selectError = (state) => state.posts.error;
export const selectFeedPagination = (state) => state.posts.feedPagination;
export const selectMyFeedPagination = (state) => state.posts.myFeedPagination;
